spring:
  application:
    name: quickclock-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/quickclock}
    username: ${DATABASE_USERNAME:quickclock}
    password: ${DATABASE_PASSWORD:quickclock}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}
