CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE company_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    half_day_value_cents BIGINT NOT NULL DEFAULT 0,
    monday_active BOOLEAN NOT NULL DEFAULT TRUE,
    tuesday_active BOOLEAN NOT NULL DEFAULT TRUE,
    wednesday_active BOOLEAN NOT NULL DEFAULT TRUE,
    thursday_active BOOLEAN NOT NULL DEFAULT TRUE,
    friday_active BOOLEAN NOT NULL DEFAULT TRUE,
    saturday_active BOOLEAN NOT NULL DEFAULT FALSE,
    sunday_active BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_company_settings_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT uq_company_settings_company UNIQUE (company_id),
    CONSTRAINT ck_company_settings_half_day_value CHECK (half_day_value_cents >= 0)
);

CREATE TABLE work_day (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    worked_before_lunch BOOLEAN NOT NULL DEFAULT FALSE,
    worked_after_lunch BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_work_day_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT uq_work_day_company_date UNIQUE (company_id, work_date)
);

CREATE TABLE additional_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    service_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount_cents BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_additional_service_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT ck_additional_service_amount CHECK (amount_cents >= 0)
);

CREATE TABLE estimate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    estimate_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount_cents BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    approved_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_estimate_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT ck_estimate_amount CHECK (amount_cents >= 0),
    CONSTRAINT ck_estimate_status CHECK (status IN ('DRAFT', 'APPROVED', 'CANCELED'))
);

CREATE TABLE estimate_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id BIGINT NOT NULL,
    previous_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_estimate_history_estimate FOREIGN KEY (estimate_id) REFERENCES estimate(id)
);

CREATE TABLE financial_income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT NOT NULL,
    income_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount_cents BIGINT NOT NULL,
    paid_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_financial_income_company FOREIGN KEY (company_id) REFERENCES company(id),
    CONSTRAINT ck_financial_income_amount CHECK (amount_cents >= 0),
    CONSTRAINT ck_financial_income_source_type CHECK (source_type IN ('WORK_REPORT', 'ADDITIONAL_SERVICE', 'APPROVED_ESTIMATE'))
);

CREATE TABLE expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_date DATE NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount_cents BIGINT NOT NULL,
    category VARCHAR(120),
    payment_method VARCHAR(40) NOT NULL,
    installment_number INTEGER,
    installment_total INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_expense_amount CHECK (amount_cents >= 0),
    CONSTRAINT ck_expense_payment_method CHECK (payment_method IN ('CASH', 'PIX', 'DEBIT', 'CREDIT_CARD', 'OTHER')),
    CONSTRAINT ck_expense_installment_number CHECK (installment_number IS NULL OR installment_number > 0),
    CONSTRAINT ck_expense_installment_total CHECK (installment_total IS NULL OR installment_total > 0)
);

CREATE INDEX idx_work_day_company_month ON work_day(company_id, work_date);
CREATE INDEX idx_additional_service_company_month ON additional_service(company_id, service_date);
CREATE INDEX idx_estimate_company_approved_month ON estimate(company_id, approved_at);
CREATE INDEX idx_financial_income_company_month ON financial_income(company_id, income_date);
CREATE INDEX idx_expense_month ON expense(expense_date);
